const articles = [
    {
    id: 'learn-react',
    title: 'The fastest way to learn react',
    content: [`Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react.`, `Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react.`, `Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react.`, `Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react.`
]},
{
    id: 'learn-html',
    title: 'The fastest way to learn HTML',
    content: [`Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react.`, `Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react.`, `Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react.`, `Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react.`]
},
{
    id: 'learn-css',
    title: 'The fastest way to learn CSS',
    content: [`Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react.`, `Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react.`, `Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react.`, `Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react. Welcome to react Welcome to react Welcome to react.`]
},
]

export default articles